# Generated by Django 4.0.2 on 2022-02-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_6', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='eu_sales',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='global_sales',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='jp_sales',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='na_sales',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='other_sales',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='publisher',
        ),
    ]
