# Generated by Django 4.0.2 on 2022-02-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('notebook', 'notebook'), ('accessories', 'accessories'), ('mobile', 'mobile'), ('pc', 'pc')], default='mobile', max_length=20),
        ),
    ]
