# Generated by Django 4.0.2 on 2022-02-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_group_alter_reviews_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pc', 'pc'), ('notebook', 'notebook'), ('accessories', 'accessories'), ('mobile', 'mobile')], default='mobile', max_length=20),
        ),
    ]
