# Generated by Django 4.0.2 on 2022-02-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('mobile', 'mobile'), ('notebook', 'notebook'), ('accessories', 'accessories'), ('pc', 'pc')], default='mobile', max_length=20),
        ),
    ]
