# Generated by Django 4.0.2 on 2022-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pc', 'pc'), ('mobile', 'mobile'), ('notebook', 'notebook'), ('accessories', 'accessories')], default='mobile', max_length=20),
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
