# Generated by Django 4.0.2 on 2022-02-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_group_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pc', 'pc'), ('mobile', 'mobile'), ('accessories', 'accessories'), ('notebook', 'notebook')], default='mobile', max_length=20),
        ),
    ]
