# Generated by Django 4.0.2 on 2022-02-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_group_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('mobile', 'mobile'), ('pc', 'pc'), ('accessories', 'accessories'), ('notebook', 'notebook')], default='mobile', max_length=20),
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
