# Generated by Django 4.0.2 on 2022-02-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_group_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('notebook', 'notebook'), ('mobile', 'mobile'), ('accessories', 'accessories'), ('pc', 'pc')], default='mobile', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_products', to='main.product', verbose_name='Продукт'),
        ),
    ]
