# Generated by Django 4.0.2 on 2022-02-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_group_alter_reviews_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('accessories', 'accessories'), ('pc', 'pc'), ('mobile', 'mobile'), ('notebook', 'notebook')], default='mobile', max_length=20),
        ),
    ]
