# Generated by Django 4.0.2 on 2022-02-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_reviews_email_remove_reviews_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('accessories', 'accessories'), ('mobile', 'mobile'), ('notebook', 'notebook'), ('pc', 'pc')], default='mobile', max_length=20),
        ),
    ]
