# Generated by Django 4.0.2 on 2022-02-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('accessories', 'accessories'), ('pc', 'pc'), ('mobile', 'mobile'), ('notebook', 'notebook')], default='mobile', max_length=20),
        ),
    ]
