# Generated by Django 4.0.2 on 2022-02-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('mobile', 'mobile'), ('accessories', 'accessories'), ('notebook', 'notebook'), ('pc', 'pc')], default='mobile', max_length=20),
        ),
    ]
