# Generated by Django 4.0.2 on 2022-02-04 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_description', models.TextField(null=True)),
                ('year_of_manufacture', models.DateTimeField(auto_now_add=True)),
                ('ready_for_use', models.BooleanField(default=True)),
                ('wikipedia', models.URLField(default='https://ru.wikipedia.org/')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('photo_auto', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=64)),
                ('invoice', models.FileField(upload_to='')),
                ('user_uuid', models.UUIDField(editable=False)),
                ('discount_size', models.DecimalField(decimal_places=10, max_digits=10)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('Year_of_opened', models.DateTimeField(auto_now_add=True)),
                ('photo_park', models.ImageField(blank=True, null=True, upload_to='')),
                ('park_description', models.TextField(null=True)),
                ('cars', models.ManyToManyField(to='lesson_4.Car', verbose_name='Auto-park')),
            ],
        ),
    ]
