# Generated by Django 4.0.2 on 2022-05-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_options'),
        ('article', '0002_alter_authorarticle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorite',
            field=models.ManyToManyField(to='user.Profile'),
        ),
    ]
