# Generated by Django 4.0.2 on 2022-07-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.authorarticle', verbose_name='Автор статьи'),
        ),
    ]
